const techStackImages: { [key: string]: string } = {
  REACT: '/icons/techStackIcons/react.svg',
  VUE: '/icons/techStackIcons/vue.svg',
  NEXTJS: '/icons/techStackIcons/nextjs.svg',
  JAVASCRIPT: '/icons/techStackIcons/javascript.svg',
  TYPESCRIPT: '/icons/techStackIcons/typescript.svg',
  SPRING: '/icons/techStackIcons/spring.svg',
  NODEJS: '/icons/techStackIcons/nodejs.svg',
  FLASK: '/icons/techStackIcons/flask.svg',
  NESTJS: '/icons/techStackIcons/nestjs.svg',
  DJANGO: '/icons/techStackIcons/django.svg',
  JAVA: '/icons/techStackIcons/java.svg',
  MYSQL: '/icons/techStackIcons/mysql.svg',
  MONGODB: '/icons/techStackIcons/mongodb.svg',
  REDIS: '/icons/techStackIcons/redis.svg',
  KOTLIN: '/icons/techStackIcons/kotlin.svg',
  SWIFT: '/icons/techStackIcons/swift.svg',
  FLUTTER: '/icons/techStackIcons/flutter.svg',
  PYTHON: '/icons/techStackIcons/python.svg',
  TENSORFLOW: '/icons/techStackIcons/tensorflow.svg',
  PYTORCH: '/icons/techStackIcons/pytorch.svg',
  UNITY: '/icons/techStackIcons/unity.svg',
  UNREAL: '/icons/techStackIcons/unrealengine.svg',
  C: '/icons/techStackIcons/c.svg',
  CPP: '/icons/techStackIcons/cpp.svg',
  CSHARP: '/icons/techStackIcons/csharp.svg',
};

export default techStackImages;
