const algorithmTierImages: { [key: string]: string } = {
  RUBY1: '/icons/algorithmTierIcons/ruby1.svg',
  RUBY2: '/icons/algorithmTierIcons/ruby2.svg',
  RUBY3: '/icons/algorithmTierIcons/ruby3.svg',
  RUBY4: '/icons/algorithmTierIcons/ruby4.svg',
  RUBY5: '/icons/algorithmTierIcons/ruby5.svg',
  DIAMOND1: '/icons/algorithmTierIcons/diamond1.svg',
  DIAMOND2: '/icons/algorithmTierIcons/diamond2.svg',
  DIAMOND3: '/icons/algorithmTierIcons/diamond3.svg',
  DIAMOND4: '/icons/algorithmTierIcons/diamond4.svg',
  DIAMOND5: '/icons/algorithmTierIcons/diamond5.svg',
  PLATINUM1: '/icons/algorithmTierIcons/platinum1.svg',
  PLATINUM2: '/icons/algorithmTierIcons/platinum2.svg',
  PLATINUM3: '/icons/algorithmTierIcons/platinum3.svg',
  PLATINUM4: '/icons/algorithmTierIcons/platinum4.svg',
  PLATINUM5: '/icons/algorithmTierIcons/platinum5.svg',
  GOLD1: '/icons/algorithmTierIcons/gold1.svg',
  GOLD2: '/icons/algorithmTierIcons/gold2.svg',
  GOLD3: '/icons/algorithmTierIcons/gold3.svg',
  GOLD4: '/icons/algorithmTierIcons/gold4.svg',
  GOLD5: '/icons/algorithmTierIcons/gold5.svg',
  SILVER1: '/icons/algorithmTierIcons/silver1.svg',
  SILVER2: '/icons/algorithmTierIcons/silver2.svg',
  SILVER3: '/icons/algorithmTierIcons/silver3.svg',
  SILVER4: '/icons/algorithmTierIcons/silver4.svg',
  SILVER5: '/icons/algorithmTierIcons/silver5.svg',
  BRONZE1: '/icons/algorithmTierIcons/bronze1.svg',
  BRONZE2: '/icons/algorithmTierIcons/bronze2.svg',
  BRONZE3: '/icons/algorithmTierIcons/bronze3.svg',
  BRONZE4: '/icons/algorithmTierIcons/bronze4.svg',
  BRONZE5: '/icons/algorithmTierIcons/bronze5.svg',
  UNRANKED: '/icons/algorithmTierIcons/unranked.svg',
};

export default algorithmTierImages;
